<?php

declare(strict_types=1);

namespace Cone\Bazar\Database\Factories;

use Cone\Bazar\Enums\DiscountRuleValueType;
use Cone\Bazar\Models\DiscountRule;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Arr;

class DiscountRuleFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model>
     */
    protected $model = DiscountRule::class;

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName(): string
    {
        return $this->model::getProxiedClass();
    }

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'active' => true,
            'name' => $this->faker->words(3, true),
            'rules' => [],
            'stackable' => false,
            'discountable_type' => Arr::random(DiscountRule::getDiscountableTypes()),
            'value_type' => DiscountRuleValueType::TOTAL,
        ];
    }
}
