<?php

namespace Cone\Bazar\Database\Factories;

use Cone\Bazar\Models\Order;
use Illuminate\Database\Eloquent\Factories\Factory;

class OrderFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Order::class;

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName(): string
    {
        return $this->model::getProxiedClass();
    }

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'discount' => 0,
            'currency' => 'usd',
        ];
    }
}
