<?php

namespace Cone\Bazar\Database\Factories;

use Cone\Bazar\Models\Transaction;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Arr;

class TransactionFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Transaction::class;

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName(): string
    {
        return $this->model::getProxiedClass();
    }

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'driver' => 'cash',
            'amount' => mt_rand(10, 1000) / 10,
            'type' => Arr::random([Transaction::PAYMENT, Transaction::REFUND]),
        ];
    }
}
