<?php

namespace Cone\Bazar\Database\Factories;

use Cone\Bazar\Bazar;
use Cone\Bazar\Models\Variant;
use Cone\Root\Models\Meta;
use Illuminate\Database\Eloquent\Factories\Factory;

class VariantFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Variant::class;

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName(): string
    {
        return $this->model::getProxiedClass();
    }

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'alias' => null,
        ];
    }

    /**
     * Configure the model factory.
     */
    public function configure(): static
    {
        return $this->afterMaking(static function (Variant $variant): void {
            $variant->setRelation('metaData', $variant->metaData()->makeMany([
                ['key' => 'price_'.strtolower(Bazar::getCurrency()), 'value' => mt_rand(10, 100)],
            ]));
        })->afterCreating(static function (Variant $variant): void {
            $variant->metaData->each(static function (Meta $meta) use ($variant) {
                $meta->setAttribute('metable_id', $variant->getKey())->save();
            });
        });
    }
}
