name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        php: ["7.3", "7.4", "8.0"]
        stability: [prefer-stable]

    name: PHP ${{ matrix.os }} - ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, fileinfo, exif
          tools: composer:v2
          coverage: pcov

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Send coverage to Coveralls
        if: matrix.php == '7.3'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require twinh/php-coveralls
          php-coveralls -v
