name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      # https://github.com/laravel/framework/pull/34245
      - name: Fix the framework
        run: |
          sed -i -e 's#^\s*.links. => \$this->linkCollection(),$#             "links" => $this->linkCollection()->toArray(),#' vendor/laravel/framework/src/Illuminate/Pagination/LengthAwarePaginator.php

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
